In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
test_dataset = pd.read_csv('/kaggle/input/energy-consumption-dataset-linear-regression/test_energy_data.csv')
train_dataset = pd.read_csv('/kaggle/input/energy-consumption-dataset-linear-regression/train_energy_data.csv')
X_test = test_dataset.iloc[:, :-1].values
y_test = test_dataset.iloc[:, -1].values
X_train = train_dataset.iloc[:, :-1].values
y_train = train_dataset.iloc[:, -1].values

In [3]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
categorical_values = [0,5]
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), categorical_values)], remainder='passthrough')
X_train = np.array(ct.fit_transform(X_train))
X_test = np.array(ct.transform(X_test))

In [4]:
print(X_train)

[[0.0 0.0 1.0 ... 76 10 29.84]
 [1.0 0.0 0.0 ... 66 45 16.72]
 [0.0 1.0 0.0 ... 37 17 14.3]
 ...
 [1.0 0.0 0.0 ... 88 20 32.18]
 [0.0 0.0 1.0 ... 67 37 16.48]
 [1.0 0.0 0.0 ... 57 11 31.4]]


In [5]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [6]:
y_pred = regressor.predict(X_test)

In [7]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9999999997063025